apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-api-ingress
  namespace: payments
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /\$1
spec:
  rules:
    - host: payment.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: payment-api
                port:
                  number: 8001
