apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: notificationdb
  MAIL_USERNAME: d302a63a4256cf
  MAIL_PASSWORD: 17316a9b8b0de8

